name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            record: true
        env:
            # overwrite commit message sent to Cypress Cloud
            # COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
            # re-enable PR comment bot
            COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}

      - name: Upload screenshots Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: cypress-screenshots
            path: cypress/screenshots
        
      - name: Upload Video artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: cypress-videos
            path: cypress/videos
